version: 2

project_name: studio-mcp

before:
  hooks:
    - go mod tidy
    - go generate ./...
    # Sync package.json version with git tag
    - ./scripts/sync-version.sh

builds:
  - id: studio-mcp
    binary: studio-mcp
    main: ./main.go
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64

archives:
  - id: default
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

# Generate Linux packages
nfpms:
  - id: packages
    package_name: studio-mcp
    vendor: Studio MCP
    description: Make any CLI command an MCP server
    maintainer: Martin Emde <me@martinemde.com>
    homepage: https://github.com/studio-mcp/studio-mcp
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - archlinux

# Homebrew tap (optional - can be added later)
# brews:
#   - name: studio-mcp
#     repository:
#       owner: studio-mcp
#       name: homebrew-tap
#     homepage: https://github.com/studio-mcp/studio-mcp
#     description: Make any CLI command an MCP server
#     license: MIT

release:
  draft: false
  replace_existing_draft: true
  prerelease: auto
  mode: replace
